version: '3'
services:

    jenkins:
        restart: always
        image: docker.gillsoft.org/jenkins-gillsoft
        ports:
            - "18081:8080"
        environment:
            - JENKINS_OPTS="--prefix=/jenkins"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /data/files/jenkins/home:/var/jenkins_home 
